baseURL = "https://springrunner.github.io"
title = "SpringRunner"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = "UA-131208921-1"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = ""
title404 = "페이지를 찾을 수 없습니다."

[params.assets]
favicon = "favicon.ico"
customCSS = ["assets/css/custom.css"]
customJS = []
gopher = ""                             # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "SpringRunner"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"]  # boolean / array of sections
hideEntryMeta = ["page"]        # boolean / array of sections
showReadingTime = false
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","social_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "|"

[params.social]
codepen = ""
email = "springrunner.kr@gmail.com"
facebook = ""
github = "springrunner"
gitlab = ""
instagram = ""
linkedin = ""
twitter = ""
telegram = ""
google_scholar = ""
youtube = ""

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = ""
repository = ""
branch = ""

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = true
issueTerm = "pathname"                  # pathname / url / title

[params.comments.utterances.github]
username = "springrunner"
repository = "springrunner-site"

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name   = "about us"
url    = "/"
weight = -10

[[menu.main]]
name   = "training"
url    = "/training/"
weight = 10

#[[menu.main]]
#name   = "posts"
#url    = "/post/"
#weight = 20

#[[menu.main]]
#name = "Repo"
#weight = -10
#identifier = "repository"
#url = "https://github.com/springrunner"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
